import test from 'node:test';
import assert from 'node:assert/strict';
import {E} from './economy-modules.mjs';
test('wages, consumption and wholesale conserve currency over long runs',()=>{const e=E.createEconomy();for(let n=0;n<500;n++)E.economyRound(e);assert.equal(E.totalMoney(e),15000);for(const key of ['shop','producer','player','bank'])assert.ok(e[key]>=0);assert.ok(e.households.every(h=>h.cash>=0));assert.ok(Object.values(e.stock).every(n=>n>=0));});
test('player purchases charge the finite wallet and really remove stock',()=>{const e=E.createEconomy(),p=E.price(e,'bread');assert.equal(E.buyGood(e,'bread',p),true);assert.equal(e.player,1000-p);assert.equal(e.stock.bread,23);assert.equal(E.totalMoney(e),15000);e.player=0;const stock=e.stock.bread;assert.equal(E.buyGood(e,'bread',p),false);assert.equal(e.stock.bread,stock);assert.equal(E.buyGood(e,'unknown',1),false);assert.equal(E.buyGood(e,'bread',-1),false);});
test('delivery cannot duplicate cargo and transfers merchant funds to player and producer',()=>{const e=E.createEconomy();assert.equal(E.deliverCargo(e),false);assert.equal(E.pickupCargo(e),true);assert.equal(E.pickupCargo(e),false);assert.equal(e.warehouse.bread,50);assert.equal(E.deliverCargo(e),true);assert.equal(e.player,1040);assert.equal(e.stock.bread,34);assert.equal(E.totalMoney(e),15000);assert.equal(E.deliverCargo(e),false);e.shop=0;E.pickupCargo(e);assert.equal(E.deliverCargo(e),false);assert.equal(e.cargo,10);});
test('production shutdown depletes stocks and raises prices and unmet needs',()=>{const normal=E.createEconomy(),shock=E.createEconomy();shock.supply=0;for(let n=0;n<15;n++){E.economyRound(normal);E.economyRound(shock);}assert.ok(shock.stock.bread<normal.stock.bread);assert.ok(E.price(shock,'bread')>E.price(normal,'bread'));assert.ok(shock.households.some(h=>h.hunger>0));assert.equal(E.totalMoney(shock),15000);});
test('issuance is explicit and persists; old or corrupt saves fall back safely',()=>{const e=E.createEconomy();E.issueMoney(e);assert.equal(E.totalMoney(e),16000);assert.equal(e.issued,1000);const restored=E.restoreEconomy(JSON.parse(JSON.stringify(e)));assert.equal(E.totalMoney(restored),16000);assert.equal(restored.issued,1000);assert.equal(E.restoreEconomy(null).player,1000);e.shop=-1;assert.equal(E.restoreEconomy(e).shop,3000);});
test('simulation timing is frame rate independent and ignores long suspended deltas',()=>{const a=E.createEconomy(),b=E.createEconomy();for(let i=0;i<1800;i++)E.tickEconomy(a,1/60);for(let i=0;i<900;i++)E.tickEconomy(b,1/30);assert.equal(a.round,b.round);assert.deepEqual(a.stock,b.stock);const c=E.createEconomy();E.tickEconomy(c,3600);assert.equal(c.round,0);});
