import {worldToMap,mapToWorld,distance,routeLength} from './map-navigation.js';
export function mountMap(el,{base,world,player,markers,navigation,onNavigate,onClear,onClose}){
  el.innerHTML='<div class="map-toolbar"><b>番薯寮 · 地圖</b><input id="mapSearch" placeholder="搜尋地點 / 居民" aria-label="搜尋地點或居民"><select id="mapFilter" aria-label="地圖分類"><option value="all">全部</option><option value="shop">商店</option><option value="resident">居民</option><option value="job">挖礦 / 送貨</option><option value="mission">任務</option></select><button data-map="out" aria-label="縮小">−</button><button data-map="in" aria-label="放大">＋</button><button data-map="home">定位</button><button data-map="close">關閉</button></div><div class="map-stage"><canvas aria-label="可拖曳縮放，點選地圖設定導航"></canvas><div id="mapResults"></div></div><div class="map-footer"><span id="mapSelection">點選標記或地圖 · 雙指縮放 / 單指拖曳</span><button data-map="go" disabled>導航</button><button data-map="clear">清除路線</button></div>';
  const cv=el.querySelector('canvas'),ctx=cv.getContext('2d'),search=el.querySelector('#mapSearch'),filter=el.querySelector('#mapFilter'),results=el.querySelector('#mapResults'),label=el.querySelector('#mapSelection'),go=el.querySelector('[data-map="go"]');
  const view={x:0,z:20,width:1,height:1,scale:1};let selected=null,fit=true,disposed=false;
  const visible=()=>markers.filter(m=>(filter.value==='all'||m.category===filter.value)&&m.label.toLowerCase().includes(search.value.trim().toLowerCase()));
  function select(m){selected=m;go.disabled=false;label.textContent=m.label+' · '+(m.detail||'')+' · 直線 '+Math.round(distance(player.pos,m))+' m';navigation=onNavigate(m);label.textContent=m.label+' · 導航 '+Math.round(routeLength(navigation.path))+' m';draw();}
  function draw(){if(disposed)return;const dpr=Math.min(devicePixelRatio||1,2),box=cv.getBoundingClientRect();view.width=Math.max(1,box.width);view.height=Math.max(1,box.height);if(fit){view.scale=Math.min(view.width,view.height)/580;fit=false;}cv.width=Math.round(view.width*dpr);cv.height=Math.round(view.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#17251e';ctx.fillRect(0,0,view.width,view.height);
    const corner=worldToMap({x:-world/2,z:-world/2},view);ctx.drawImage(base,corner.x,corner.z,world*view.scale,world*view.scale);
    if(navigation?.path?.length){ctx.strokeStyle='#f2c230';ctx.lineWidth=3;ctx.beginPath();navigation.path.forEach((p,i)=>{const t=worldToMap(p,view);i?ctx.lineTo(t.x,t.z):ctx.moveTo(t.x,t.z);});ctx.stroke();}
    for(const m of visible()){const p=worldToMap(m,view);if(p.x<0||p.z<0||p.x>view.width||p.z>view.height)continue;ctx.fillStyle=m.color||'#fff';ctx.beginPath();ctx.arc(p.x,p.z,selected===m?8:m.category==='resident'?3.5:5,0,Math.PI*2);ctx.fill();if(m.category!=='resident'||selected===m||search.value){ctx.font='12px system-ui';ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='#101719';ctx.strokeText(m.label,p.x,p.z-10);ctx.fillStyle='#fff';ctx.fillText(m.label,p.x,p.z-10);}}
    const p=worldToMap(player.pos,view);ctx.fillStyle='#ff6363';ctx.beginPath();ctx.arc(p.x,p.z,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#fff';ctx.font='12px system-ui';ctx.textAlign='left';ctx.fillText('北 ↑ · 比例 '+Math.round(100/view.scale)+' m / 100px',10,18);
  }
  const refresh=()=>{results.replaceChildren();if(search.value.trim())for(const m of visible().slice(0,8)){const b=document.createElement('button');b.textContent=m.label;b.onclick=()=>{view.x=m.x;view.z=m.z;select(m);};results.append(b);}draw();};search.oninput=refresh;filter.onchange=refresh;
  el.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{const a=b.dataset.map;if(a==='close'){onClose();return;}if(a==='in')view.scale=Math.min(8,view.scale*1.4);if(a==='out')view.scale=Math.max(.15,view.scale/1.4);if(a==='home'){view.x=player.pos.x;view.z=player.pos.z;}if(a==='clear'){onClear();navigation=null;label.textContent='路線已清除';}if(a==='go'&&selected){navigation=onNavigate(selected);label.textContent=selected.label+' · 道路參考路線 '+Math.round(routeLength(navigation.path))+' m';}draw();});
  const pointers=new Map();let gesture=null,dragged=false;
  const point=e=>{const b=cv.getBoundingClientRect();return {x:e.clientX-b.left,z:e.clientY-b.top};};
  const snapshot=()=>{const a=[...pointers.values()];gesture=a.length>=2?{center:{x:(a[0].x+a[1].x)/2,z:(a[0].z+a[1].z)/2},span:Math.max(1,distance(a[0],a[1]))}:a.length?{center:a[0]}:null;};
  cv.onpointerdown=e=>{e.preventDefault();cv.setPointerCapture(e.pointerId);pointers.set(e.pointerId,point(e));if(pointers.size===1)dragged=false;else dragged=true;snapshot();};
  cv.onpointermove=e=>{if(!pointers.has(e.pointerId))return;const old=gesture;pointers.set(e.pointerId,point(e));snapshot();if(!old||!gesture)return;const delta=distance(old.center,gesture.center);if(delta>1||pointers.size>1)dragged=true;const anchor=mapToWorld(old.center,view);if(old.span&&gesture.span)view.scale=Math.max(.15,Math.min(8,view.scale*gesture.span/old.span));view.x=anchor.x-(gesture.center.x-view.width/2)/view.scale;view.z=anchor.z-(gesture.center.z-view.height/2)/view.scale;draw();};
  cv.onpointerup=e=>{if(!pointers.has(e.pointerId))return;if(!dragged&&pointers.size===1){const p=point(e),m=visible().map(m=>({m,d:distance(worldToMap(m,view),p)})).filter(v=>v.d<16).sort((a,b)=>a.d-b.d)[0];select(m?.m||{...mapToWorld(p,view),label:'自訂目的地',category:'custom'});}pointers.delete(e.pointerId);snapshot();};
  cv.onpointercancel=cv.onlostpointercapture=e=>{pointers.delete(e.pointerId);dragged=true;snapshot();};
  cv.onwheel=e=>{e.preventDefault();const p=point(e),anchor=mapToWorld(p,view);view.scale=Math.max(.15,Math.min(8,view.scale*Math.exp(-e.deltaY*.002)));view.x=anchor.x-(p.x-view.width/2)/view.scale;view.z=anchor.z-(p.z-view.height/2)/view.scale;draw();};
  const observer=new ResizeObserver(draw);observer.observe(cv);draw();return ()=>{disposed=true;observer.disconnect();pointers.clear();};
}
